# MOST USED FUNCTIONS


## string functions

1. `LENGTH()`: Returns the length of the string in the column.


2. `LOWER()` and `UPPER()`: Converts all characters in the string column to lowercase (LOWER) or uppercase (UPPER).


3. `TRIM()`: Removes leading and trailing spaces from the string in the column.


4. `SUBSTR(string, start_position, [length])`: Extracts a substring from a string, starting at a specified position, and optionally for a specified number of characters.


5. `LEFT(column, 5)`:  Extracts a specified number of characters from the left (beginning) of a string.


6. `CONCAT(col1, col2)`: Concatenates two or more strings together.


```sql
SELECT
  LENGTH(first_name) AS lenght_of_first_name,
  LOWER(first_name) AS lower_case,
  UPPER(first_name) AS upper_case,
  TRIM(first_name) AS NAME,
  SUBSTR(first_name, 1, 5) AS NAME_5_CHAR,
  SUBSTR(last_name, 3) AS remaining_name,
  LEFT(first_name, 3) AS short_name,
  CONCAT(first_name, '_',  last_name) AS FULL_NAME
FROM employees;
```


## Aggregate Functions:

These functions can also serve as window functions.

1. `AVG()` : Computes the average value of a set of rows within the window or partition or across all rows
   
```sql
SELECT 
      AVG(SALARY) AS AVERAGE_SALARY,
      AVG(SALARY) OVER (PARTITION BY DEPT) AS AVG_DEPT_SALARY
FROM employees;

```

\

2. `COUNT()` : Counts the number of rows in the window (partition) or across the entire result set.

```sql
SELECT 
      COUNT(DISTINCT ID) AS DIISTINCT_ID_COUNT,
      COUNT(EMP_ID) OVER (PARTITION BY DEPARTMENT) AS DEPT_EMP_COUNT
FROM employees;
```

\

3. `SUM()` : Computes the sum of values within the window (partition) or across the entire result set.

```sql
SELECT 
    SUM(SALARY) AS SALARY_TOTAL,
    SUM(SALARY) OVER (PARTITION BY DEPT) AS DEPT_SALARY_TOTAL
FROM employees;
```

\

4. `MIN()` and `MAX()`: Returns the minimum or maximum value within the window or partition.

```sql
SELECT 
      MIN(SALARY) AS MIN_SALARY,
      MAX(SALARY) AS MAX_SALARY,
      MIN(SALARY) OVER (PARTITION BY DEPT) AS MIN_DEPT_SALARY,
      MAX(SALARY) OVER (PARTITION BY DEPT) AS MAX_DEPT_SALARY
FROM employees;
```


## Non-Aggregate Functions:

1. `ABS()` : Returns the absolute value of each number in the column.


2. `CEIL()` or `CEILING()` : Returns the smallest integer value greater than or equal to each number in the column.


3. `FLOOR()` : Returns the largest integer value less than or equal to each number in the column.


4. `ROUND(col, 2)`: Rounds the values in cola to 2 decimal places.


5. `POWER(col, n)`: Returns the value of the column raised to the power n.


6. `SQRT()`: Returns the square root of each number in the column.


7. `EXP()`: Returns e raised to the power of each number in the column.


8. `LOG()`: Returns the natural logarithm of each number in the column.


9. `TRUNCATE(col, n)`: Truncates (cuts off) the values in the column to n decimal places, without `rounding.`



## Window Functions


1. `ROW_NUMBER()`: Assigns a unique sequential integer to rows within a partition of a result set, starting at 1 for the first row in each partition.

This assigns a unique rank based on the salary, with the highest salary getting rank 1.

```
SELECT 
      ROW_NUMBER() OVER (PARTITION BY XYZ ORDER BY salary DESC) AS rank
FROM employees;
```

2. `RANK()`: Assigns a rank to each row within a partition of a result set, with the same rank assigned to rows with equal values. The next distinct value(s) are given a rank that skips numbers if there are ties.

If two employees have the same salary, they will receive the same rank, and the next rank will skip accordingly (e.g., 1, 2, 2, 4).

```
SELECT 
      RANK() OVER (PARTITION BY XYZ ORDER BY salary DESC) AS rank
FROM employees;
```



3. `DENSE_RANK()`: Similar to `RANK()`, but it does not skip ranks after ties.

If two employees have the same salary, they will receive the same rank, but the next rank will continue sequentially (e.g., 1, 2, 2, 3).

```
SELECT 
      DENSE_RANK() OVER (PARTITION BY XYZ ORDER BY salary DESC) AS rank
FROM employees;
```


4. `NTILE(n)`: Divides the rows in an ordered partition into n buckets or groups, and assigns a bucket number to each row. This is useful for distributing rows into quantiles.

This divides the employees into four quartiles based on their salary.

```
SELECT 
      employee_id, salary,
      NTILE(4) OVER (ORDER BY salary DESC) AS quartile
FROM employees;
```

\ 

5. `LAG()` and `LEAD()`: Accesses data from previous (LAG) or subsequent (LEAD) rows in the result set, without using a self-join.

```sql
SELECT 
       LAG(salary, 1) OVER (ORDER BY salary DESC) AS previous_salary,
       LEAD(salary, 1) OVER (ORDER BY salary DESC) AS next_salary
FROM employees;

```

\

6. `FIRST_VALUE()` and `LAST_VALUE()`: Returns the first or last value in a window or partition.

```sql
SELECT 
      FIRST_VALUE(salary) OVER (ORDER BY salary DESC) AS HIGHEST_SALARY
      LAST_VALUE(salary) OVER (ORDER BY salary DESC) AS LOWEST_SALARY
FROM employees;
```

\

7. `PERCENT_RANK()`: Calculates the relative rank of the current row within a partition, expressed as a percentage.

```sql
SELECT 
       PERCENT_RANK() OVER (ORDER BY salary DESC) AS percentile_rank
FROM employees;
```

\

## Functions comparing columns:

These functions all operate on a per-row basis, evaluating or combining values from multiple columns within the same row.

1. `GREATEST(cola, colb, 0)`: Returns the greatest (largest) value from the list of columns for each row.
   
2. `LEAST(cola, colb, 0)`: Returns the smallest value among the list of arguments within a single row.
   
   
3. `COALESCE(cola, colb, 0)` : Returns the first non-null value in the column, or the default_value if all are null.


```sql
SELECT
    GREATEST(SALARY_2000, SALARY_2010) AS GREATEST_SALARY,
    LEAST(SALARY_2000, SALARY_2010) AS LEAST_SALARY,
    COALESCE(SALARY_2000, SALARY_2010) as SALARY
FROM employees;
```



## date functions

`ADDDATE("2017-06-15", INTERVAL 10 DAY):` add date adding 10 days to given date

`CURRENT_DATE() :`  return current date


`DATE("2017-06-15") :` extract date part


`DATEDIFF(END_DATE, START_DATE) :` returns difference in days


`DATE_ADD("2017-06-15", INTERVAL 10 DAY) :` add date adding 10 days to given date


`DAY("2017-06-15") :` Return the day of the month for a date:


`DAYNAME("2017-06-15") :` Return the weekday name for a date:


`HOUR("2017-06-20 09:34:00") :` Return the hour part of a datetime:

`MONTH("2017-06-15") :` Return the month part of a date:

`SUBDATE("2017-06-15", INTERVAL 10 DAY) :` Subtract 10 days from a date and return the date


`WEEK("2017-10-25") :` Return the week number for a date:


`YEAR("2017-06-15") :` Return the year part of a date:



## Some Advanced Functions

### LISTAGG

concatenates values from multiple rows into a single string.


This query lists all medications in each ID, ordered by their name of medications, with the names concatenated into a single string.

```sql
SELECT 
    ID, 
    LISTAGG(DISTINCT MEDICATIONS, ', ') WITHIN GROUP (ORDER BY MEDICATIONS) AS MED_ARRAY
FROM table_name
GROUP BY ID
```







